### PR TITLE
remove incorrect sanity check for params of get_certificate_sn()

### LINKED ISSUE #1: There is an extra (and incorrect) sanity check in the get_certificate_sn() method of SecurityWrapper class

### PR DESCRIPTION
**Pull request by ksachdeva**
Fixes #1

### CODE REVIEW

**Comment by glemercier** [comment]
@ksachdeva, can you just rework the commit message to comply with our rules:
- Lines no longer than 65 characters
- First line is the title, second line should be empty
- Detailed information can optionally be provided starting from line 3

I'll merge you patch after you make these modifications. Thanks for submitting.

**Comment by ksachdeva** [comment]
Hi @glemercier 

Have updated the title and it is now 65 characters.

**Comment by glemercier** [comment]
You changed the title of the pull request but not the "commit message" of the patch. For that you need to do "git commit --amend" on your patch, arrange the commit message, then push it again to your branch from where you issued the pull request.

**Comment by ksachdeva** [comment]
Hi @glemercier,

Is there still an issue with the commit conventions ? Let me know and I will fix it.

Regards
Kapil

**Comment by glemercier** [comment]
Merged manually after light refactoring. Thanks Kapil for the PR

**Pull request closed without merging**
